version: '2'
services:
  stargate:
    image: stargateio/stargate-4_0:v1.0.66
    ports:
      #Authentication
      - 8081:8081
      #gRPC
      - 8090:8090
    mem_limit: 2G
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=stargate
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CLUSTER_NAME=stargate
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_VERSION=4.0
      - DEVELOPER_MODE=true
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M